apiVersion: v1
kind: Pod
metadata:
  name: debugger
  labels:
    app: debugger
spec:
  containers:
  - name: curl
    image: curlimages/curl
    command: [/bin/sh]
    args: ["-ec", "while :; do echo '.'; sleep 5; done"]
