apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: test-repo-
spec:
  entrypoint: clone
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000
  templates:
  - name: clone
    inputs:
      artifacts:
      - name: repo
        path: /src
        git:
          repo: git@github.com:zon/marker.git
          revision: main
          sshPrivateKeySecret:
            name: git
            key: sshPrivateKey
          singleBranch: true
          branch: main
          depth: 1
    # volumes:
    # - name: podman-local
    #   hostPath:
    #     path: /home/zon/.local/share/containers
    container:
      # image: zvonimir/marker-builder:1.0.0
      image: gcr.io/kaniko-project/executor:latest
      # volumeMounts:
      # - mountPath: /home/podman/.local/share/containers
      #   name: podman-local
      workingDir: /src
      command: [bash]
      args:
      - -exc
      - |
        id
        podman info
        podman run ubi8 echo hello
